spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rheodms1
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
